using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

[Generator]
public sealed class ModifierGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with attributes
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            (n, _) => n is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
            (ctx, _) => (ClassDeclarationSyntax)ctx.Node);

        var compilationAndClasses = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(compilationAndClasses, Generate);
    }

    static void Generate(SourceProductionContext context,
                         System.ValueTuple<Compilation, System.Collections.Immutable.ImmutableArray<ClassDeclarationSyntax>> data)
    {
        var compilation = data.Item1;
        var classes = data.Item2;

        var attr = compilation.GetTypeByMetadataName("AutoModifierAttribute");
        var baseType = compilation.GetTypeByMetadataName("Modifier");

        if (attr == null || baseType == null)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("public static class GeneratedModifierLoader");
        sb.AppendLine("{");
        sb.AppendLine("    public static void LoadAll()");
        sb.AppendLine("    {");

        bool any = false;

        foreach (var cls in classes)
        {
            var model = compilation.GetSemanticModel(cls.SyntaxTree);
            if (!(model.GetDeclaredSymbol(cls) is INamedTypeSymbol sym) || sym.IsAbstract)
                continue;

            var a = sym.GetAttributes().FirstOrDefault(x => SymbolEqualityComparer.Default.Equals(x.AttributeClass, attr));
            if (a == null)
                continue;

            if (!InheritsFrom(sym, baseType))
                continue;

            var member = a.ConstructorArguments[0].Value as string;
            if (string.IsNullOrEmpty(member))
                continue;

            bool found = false;
            foreach (var m in sym.GetMembers(member))
                if (m.IsStatic) found = true;

            if (!found)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("MOD001", "Invalid Instance Member",
                    "'" + sym.Name + "' does not contain static member '" + member + "'",
                    "Modifiers", DiagnosticSeverity.Error, true),
                    cls.GetLocation()));
                continue;
            }

            sb.AppendLine("        _ = " + sym.ToDisplayString() + "." + member + ";");
            any = true;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        if (any)
            context.AddSource("GeneratedModifierLoader.g.cs", sb.ToString());
    }

    static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        while (type != null)
        {
            if (SymbolEqualityComparer.Default.Equals(type, baseType))
                return true;
            type = type.BaseType;
        }
        return false;
    }
}
